### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by ClaudiuA** [dresa/mill-ai#1]
Hello,
I try to run your game in eclipse and i got compile errors:
String fromStr = Lue.rivi();
String toStr = Lue.rivi();
String removeStr = Lue.rivi();
Lue cannot be ressolved.
Do you have any ideas why this happens?

**Comment by dresa** [comment]
Hi,
You should try launching the game from the GUI class, which uses the graphical user interface. The Lue class is just a simple class for reading user input from console in the text version of the program (without GUI). Just in case, I attached here a .class file of Lue which you should place among the other class files to get everything working. The legacy source is available at http://www.cs.helsinki.fi/u/wikla/JohdOhj/Sisalto/2/Lue.java
[Lue.zip](https://github.com/dresa/mill-ai/files/607068/Lue.zip)
